config/routes.rb
Rails.application.routes.draw do
  root 'pages#batman'
  get 'pages/batman'
  get 'pages/superman'
  get 'pages/batmanVsSuperman'
  get 'experiments/page1'
  get 'experiments/page2'
  get 'experiments/page3'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
	def page1 
	end
	def page2 
	end
	def page3
	end	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def batman
	end
	def superman
	end
	def batmanVsSuperman
	end		
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/experiments/page1.html.erb
<p>page1</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero sapiente atque quos ad aut qui? Iste cum recusandae molestiae doloremque, deserunt eum maiores reiciendis voluptas. Doloremque necessitatibus, architecto quam et?</p>

app/views/experiments/page2.html.erb
<p>page2</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque recusandae provident sunt dolores dolore asperiores in aliquid magni, adipisci expedita? Molestias, vel velit fuga eius voluptatibus omnis, numquam nesciunt obcaecati.</p>

app/views/experiments/page3.html.erb
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium inventore veritatis, quae nesciunt placeat fugiat aspernatur saepe iusto nobis necessitatibus soluta blanditiis, laboriosam numquam autem cumque neque illo totam accusamus!</p>

app/views/layouts/_navbar.html.erb
	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">Brand</a>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
				<ul class="nav navbar-nav">
					<li><%= link_to 'pag1', experiments_page1_path %></li>
					<li><%= link_to 'pag2', experiments_page2_path %></li>
					<li><%= link_to 'pag3', experiments_page3_path %></li>
				</ul>
			</div>
		</div>
	</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Superheroes</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
	<%= render partial: 'layouts/navbar' %>
	<%= yield %>

</body>
</html>

app/views/layouts/bootstrap.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>HeroesB</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
	<%= render partial: 'layouts/navbar' %>

	<%= yield %>

</body>
</html>

app/views/pages/batman.html.erb
<p>I am Batman</p>

app/views/pages/batmanVsSuperman.html.erb
<p>batman vs superman</p>
<%= image_tag 'batman' %>
<%= link_to 'Batman', pages_batman_path %>
<%= image_tag 'superman' %>
<%= link_to 'Superman', pages_superman_path %>

app/views/pages/superman.html.erb
<p>This looks like a job for Superman"
</p>